name: if rss then slack
on:
  rss:
    url: ${{ secrets.RSS_WALLSTREETCN_LIVE }}
jobs:
  slack:
    - name: Send a message to Slack
    env:
      SLACK_WEBHOOK: ${{ secrets.SLACK_MEDIA_HOOK }}
    uses: Ilshidur/action-slack@2.1.0
    with:
      args: |
        New rss items

        > ${{ on.rss.ouputs.contentSnippet }}

        > <${{ on.rss.outputs.link }}|Click here> for details.
